" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2008 Dec 17
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file
endif
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
" let &guioptions = substitute(&guioptions, "t", "", "g")

" Don't use Ex mode, use Q for formatting
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
    "set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  " set hlsearch
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

else

  set autoindent		" always set autoindenting on

endif " has("autocmd")

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

" I add the following one, the lines before is vim example
filetype plugin on
filetype indent on

set autoread
set wildmenu
set showmatch
set noerrorbells
set novisualbell
" set t_vb
set tm=500
set nowb
" set noswapfile

"                                                                                      
" tab new is very good in small monitor computer.
set expandtab
set ts=4
set cindent
set shiftwidth=4
set nu
set backspace=2
set backup
set backupdir=d:\git\backup
set nowrap
set ignorecase
map <silent> <S-j> <C-f>
map <silent> <S-k> <C-b>
map <silent> <S-w> <C-w>
map <silent> <S-t> <C-t>
map <silent> <S-y> <C-]>
nmap <silent> <S-m> :silent noh<CR>
set gcr=a:block-blinkon0
" set hls
set noincsearch " press enter then search
set virtualedit=all
set scrolloff=5
" set report=0
set novisualbell
" set bg=dark
set bg=light
set cino=g0t0
" hi clear
hi LineNr ctermfg=grey
" hi PreProc ctermfg=white
set noeb
""""""""""""""""""""""""""""""
" Tag list (ctags)
""""""""""""""""""""""""""""""
let Tlist_Ctags_Cmd = '/usr/bin/ctags'
let Tlist_Show_One_File = 1
let Tlist_Exit_OnlyWindow = 1
map <silent> <S-L> <esc> :Tlist <CR>
let Tlist_Exit_OnlyWindow=1
let Tlist_File_Fold_Auto_Close=0
let Tlist_Show_Menu=1
let Tlist_Use_Right_Window = 0 " split to the left side of the screen
let Tlist_Compact_Format = 1
let Tlist_WinWidth = 35
let Tlist_Auto_Open=0 " let the tag list open automagically
let Tlist_Compact_Format = 1 " show small menu
let Tlist_Ctags_Cmd = 'ctags' " location of ctags
let Tlist_Enable_Fold_Column = 1 " do show folding tree
let Tlist_Sort_Type = "name"
"set WinManager
" let g:winManagerWindowLayout='FileExplorer|TagList'
let g:winManagerWindowLayout='FileExplorer'
nmap wm :WMToggle<cr>
nmap tl :Tlist<cr>
nmap tr :NERDTreeToggle<CR>

set list
set listchars=tab:>-,trail:-
" set listchars=tab:\.\ ,nbsp:%,trail:-
" set listchars=tab:\ \ ,nbsp:%,trail:-
" set listchars=tab:\|\ ,nbsp:%,trail:-

set foldenable
" set foldmethod=syntax
set foldmethod=manual
" set foldmethod=indent
" set foldcolumn=0
" setlocal foldlevel=1

set modifiable
set write
set path+=/usr/include/**
set tags+=../tags
set tags+=../../tags
set tags+=../../../tags
syntax on
" syntax off

" colorscheme morning is a pretty good choice
"                                                                      
"
let &termencoding=&encoding
set fileencodings=utf-8,gbk
set bsdir=buffer
set autochdir

map <silent> <F3> <esc> :set bg=dark <CR>
map <silent> <F4> <esc> :set bg=light <CR>
map <silent> <F5> <esc> :colorscheme darkblue <CR>
map <silent> <F6> <esc> :colorscheme blue <CR>
map <silent> <F7> <esc> :colorscheme default <CR>
colorscheme default
hi Constant ctermfg=5
hi Type cterm=bold ctermfg=4
hi Statement cterm=bold ctermfg=4
" set cursorcolumn                    " highlight the current column
" set cursorline                      " highlight current line
" hi cursorcolumn ctermbg=lightgrey
" hi cursorline ctermbg=300000   guibg=#400000
" hi CursorColumn ctermfg=white ctermbg=red guibg=#400000
" set bg=dark
set bg=light


let &termencoding=&encoding
set fileencodings=utf-8,gbk
set guifont=fixedsys:h24
